version: '3.7'
services:
  db:
    image: postgis/postgis:latest
    volumes:
    - .:/dockerSametinder
    ports:
      - 5432:5432
    expose:
      - 5432
  api:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 127.0.0.1:8000"
    ports:
      - '8000:8000'
    depends_on:
      - db