# Generated by Django 3.0.5 on 2021-04-26 14:29

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='geo_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(53.901, 27.5707), null=True, srid=4326),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
